# This is a basic workflow to help you get started with Actions

name: python cicd

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:  # <-- FIXED: no space before "jobs"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: testing
        run: |
          ls
          pwd
          cat main.py
          cat Dockerfile
          cat requirements.txt
